import type { Metadata } from "next";
import { GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Navbar } from "@/components/common/Navbar";
import { Footer } from "@/components/common/Footer";

const grandSlang = localFont({
  src: [
    {
      path: "../public/fonts/GrandSlang-B-Side.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--grandSlang",
});

const neueMontreal = localFont({
  src: [
    {
      path: "../public/fonts/ppneuemontreal-book.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--neueMontreal",
});

export const metadata: Metadata = {
  title: "Milan Stanojevic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GT-NNV78TSJ" />
      <body className={`${grandSlang.variable} ${neueMontreal.variable}`}>
        <Navbar />
        {children}
        <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}
